### ISSUE TITLE
MutlipleMatchesException if project pulls react.js via WebJars

### ISSUE THREAD

**Issue by dmitriyvolk** [joescii/sbt-js-test#10]
Hi!

I started using WebJars with our project today to load ReactJS. `jsTest` started to fail with the following exception:
```
[info] Writing jasmine2 assets...
org.webjars.MultipleMatchesException: Multiple matches found for jasmine.js. Please provide a more specific path, for example by including a version number.
        at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:259)
        at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:189)
        at com.joescii.sbtjs.SbtJsTestTasks$.writeJasmineAssets(SbtJsTestTasks.scala:69)
        at com.joescii.sbtjs.SbtJsTestTasks$.com$joescii$sbtjs$SbtJsTestTasks$$runTests(SbtJsTestTasks.scala:135)
        at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$3.apply(SbtJsTestTasks.scala:150)
        at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$3.apply(SbtJsTestTasks.scala:147)
...
```

Jasmine tests were executing fine before adding WebJars to `build.sbt`

build.sbt:
```
libraryDependencies ++= Seq(
"org.webjars" %% "webjars-play" % "2.4.0-1",
"org.webjars" % "react" % "0.13.3"
)
```

plugins.sbt:
```
...
libraryDependencies += "org.webjars.bower" % "jasmine" % "2.4.1" % "runtime"
addSbtPlugin("com.joescii" % "sbt-js-test" % "0.1.0")
...
addSbtPlugin("com.github.ddispaltro" % "sbt-reactjs" % "0.5.2")
```

**Comment by dmitriyvolk** [comment]
The fact that I'm pulling ReactJS doesn't seem to be relevant. Just adding WebJars seems to trigger this error

**Comment by dmitriyvolk** [comment]
On further investigation it seems that it's not the WebJars that cause trouble, but rather SbtWeb that I had to enable.

**Comment by joescii** [comment]
So your issue is resolved? If so, please comment with exactly what you did in case someone else stumbles across the same issue.

**Comment by dmitriyvolk** [comment]
No, not resolved, just not an emergency because I'm just trying React out. I would appreciate some help in figuring this out, as my experience with Sbt and JS testing is fairly limited.

**Comment by joescii** [comment]
Try removing the jasmine dependency in `plugins.sbt`.

**Comment by dmitriyvolk** [comment]
```
com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "exports" is not defined. (file:<myprojectroot>/target/sbt-js-test/assets/jasmine/console.js#27)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:954)
 ```

line 27 of said file reads:
```
global.console = exports;
```

must be some version incompatibility between what's expected by `sbt-js-test` and what `SbtWeb` pulls

**Comment by joescii** [comment]
I'm not entirely sure why we're getting this behavior. If you look at the bottom of `target/sbt-js-test/assets/jasmine/jasmine.js`, you'll see the jasmine file that the plugin is finding is version 1.3.0, which is certainly incompatible with this plugin. This is most certainly coming from the react plugin, because if you remove it AND the jasmine dependency, the sbt-js-test plugin cannot find jasmine.js at all. What I can't figure out is where it is finding jasmine 1.3.0, because the web jar for it is not showing up on any classpaths. Gotta figure out how to block that perhaps. Might even need an enhancement on this plugin to force it to select the one we want.
